# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 15:48
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
